name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'hello/pom.xml' # optional
      - name: Build with Maven
        working-directory: hello
        run: mvn -B package
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        working-directory: hello
        run: |
          ls ${{ github.workspace }}
          pwd
          ls ./target
          pwd
          java -jar target/hello-1.0-SNAPSHOT.jar
      - name: build Docker Image
        working-directory: hello
        run: |
          ls ${{ github.workspace }}
          docker build --file ./src/main/docker/Dockerfile -t irgendwas .
          docker image ls 
          docker run irgendwas
